# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"

variables:
- name: SubscriptionID
  value: 0fcbc58f-03c0-4daa-9470-840cff312d29

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Lister et supprimer les ressources 
      az resource list --subscription $(SubscriptionID) --query "[].id" -o tsv 
      $resources = az resource list --subscription $(SubscriptionID) --query "[].id" -o tsv 
      foreach ($resource in $resources) { 
        write-host $resource 
        #az resource delete --ids $resource 
      }