# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"

variables:
- name: SubscriptionID
  value: '0fcbc58f-03c0-4daa-9470-840cff312d29'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      write-host "Hello world"
      az resource list --subscription $(SubscriptionID) --query "[].id" -o ts